apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarker-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarker-db
  template:
    metadata:
      labels:
        app: bookmarker-db
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_DB
            value: "appdb"
        ports:
          - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: bookmarker-db
spec:
  ports:
    - port: 5432
  selector:
    app: bookmarker-db
